// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/17/2025, 4:41:39 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/app/spotboard-ui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/spotboard-ui/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/spotboard-ui/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/spotboard-ui/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/app/spotboard-ui/plugins/**/*.{js,ts,mjs}","/app/spotboard-ui/composables/**/*.{js,ts,mjs}","/app/spotboard-ui/utils/**/*.{js,ts,mjs}","/app/spotboard-ui/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/app/spotboard-ui/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/app/spotboard-ui/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;